# Generated by Django 5.1.5 on 2025-02-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
