# Generated by Django 5.1.5 on 2025-03-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0004_customuser_password_reset_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_required',
        ),
    ]
