# Generated by Django 5.1.5 on 2025-03-11 05:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0006_customuser_email_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_id', models.CharField(blank=True, max_length=20, null=True)),
                ('plate_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Plate number must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')])),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('In Repair', 'In Repair'), ('Unavailable', 'Unavailable')], default='Operational', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='VehicleManagementSystem.vehicle')),
            ],
        ),
    ]
