# Generated by Django 5.1.5 on 2025-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0007_vehicle_vehicledamage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
