# Generated by Django 5.1.5 on 2025-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0008_vehicle_last_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
