# Generated by Django 5.1.5 on 2025-03-25 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0009_customuser_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_battery', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_lights', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_oil', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_water', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_brakes', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_air', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_gas', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('pre_comments', models.TextField(blank=True)),
                ('pre_damages', models.TextField(blank=True)),
                ('post_battery', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_lights', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_oil', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_water', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_brakes', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_air', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_gas', models.CharField(choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20)),
                ('post_comments', models.TextField(blank=True)),
                ('post_damages', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='VehicleManagementSystem.vehicle')),
            ],
        ),
    ]
