# Generated by Django 5.1.5 on 2025-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0010_vehicleinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='completion_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pre-Delivery Only', 'Pre-Delivery Only'), ('Complete', 'Complete')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_air',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_battery',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_brakes',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_gas',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_lights',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_oil',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='post_water',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_air',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_battery',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_brakes',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_gas',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_lights',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_oil',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='pre_water',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Needs Repair', 'Needs Repair')], max_length=20, null=True),
        ),
    ]
