# Generated by Django 5.1.5 on 2025-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0011_vehicleinspection_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
