# Generated by Django 5.1.7 on 2025-04-21 12:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0013_damagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vehicle_photos'),
        ),
    ]
